---
title: "NY NOAA Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(RColorBrewer)
library(flexdashboard)
```

```{r, include = FALSE}
data("ny_noaa")

set.seed(12345)

ny_noaa_sub = ny_noaa %>% 
  sample_frac(0.25) %>% 
  separate(date, into = c("year", "month", "day"), sep = "-", remove = FALSE) %>% 
  mutate(
    year = as.numeric(year),
    month = as.numeric(month),
    day = as.numeric(day),
    prcp = ifelse(!is.na(prcp), prcp / 10, NA_real_),
    tmax = ifelse(!is.na(tmax), as.numeric(tmax) / 10, NA_real_),
    tmin = ifelse(!is.na(tmin), as.numeric(tmin) / 10, NA_real_)
  ) %>% 
  filter(year %in% 2000:2010)
```

Column {data-width = 650}
-----------------------------------------------------------------------

### Chart A: Monthly Average Minimum Temperature from 2000 to 2010

```{r}
ny_noaa_sub %>% 
  mutate(
    date = format(as.Date(date, format = "%Y-%m-%d"), "%Y-%m")
  ) %>% 
  group_by(date) %>% 
  summarise(
    mean_tmin = mean(tmin, na.rm = TRUE)
  ) %>% 
  plot_ly(
    x = ~ date,
    y = ~ mean_tmin,
    type = "scatter",
    mode = "lines"
  ) %>% 
  layout(
    xaxis = list(title = "Date"),
    yaxis = list(title = "Average Minimum Temperature\n(degrees C)")
  )
```

Column {data-width = 350}
-----------------------------------------------------------------------

### Chart B: Distribution of Maximum Temperature by Month

```{r}
ny_noaa_sub %>% 
  mutate(
    month = factor(month.name[month], levels = month.name)
  ) %>% 
  plot_ly(
    x = ~ month,
    y = ~ tmax,
    color = ~ month,
    type = "box",
    colors = "Set2"
  ) %>% 
  layout(
    xaxis = list(title = "Month"),
    yaxis = list(title = "Maximum Temperature\n(degrees C)"),
    legend = list(title = list(text = "Month"))
  )
```

### Chart C: Number of Weather Stations Functioning by Year

```{r}
ny_noaa_sub %>% 
  distinct(id, year, month, .keep_all = TRUE) %>% 
  group_by(year, month) %>% 
  count() %>% 
  mutate(
    month = factor(month.name[month], levels = month.name, ordered = TRUE)
  ) %>% 
  plot_ly(
    x = ~ year,
    y = ~ n,
    color = ~ month,
    type = "bar",
    colors = "viridis",
    alpha = .8
  ) %>% 
  layout(
    barmode = "stack",
    xaxis = list(title = "Year"),
    yaxis = list(title = "Number of Weather Stations"),
    legend = list(title = list(text = "Month"))
  )
```
